# Assignment 1 - 50 Numpy Methods 

## PIAIC 131974 - Faizan Owais

In [5]:
import numpy as np

In [25]:
arrS = np.array ([1,2,3,4,5,6,7,8,9,10])
arrS

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr2d = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
arr0 = np.zeros ((5,5))
arr0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
arr1 = np.ones ((4,4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arrEmp = np.empty ((3,2))
arrEmp

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
l = [2,4,6,8,10]
arrList = np.array((l))
arrList

array([ 2,  4,  6,  8, 10])

In [16]:
arrList.shape

(4,)

In [18]:
arr0.shape

(5, 5)

In [20]:
arrListNew = arrList.reshape (2,2)
arrListNew

array([[2, 4],
       [6, 8]])

In [21]:
arrListNew.dtype

dtype('int64')

In [22]:
arrListNew.ndim

2

In [23]:
lrange = np.arange (15)
lrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arrRand = np.random.randn ((5))
arrRand

array([-0.07004702, -0.05025089,  0.20837616, -0.68854071, -0.67131238])

In [32]:
arrList + arrRand

array([1.92995298, 3.94974911, 6.20837616, 7.31145929, 9.32868762])

In [33]:
arrRand > 0

array([False, False,  True, False, False])

In [34]:
arrRand * 2

array([-0.14009403, -0.10050178,  0.41675232, -1.37708142, -1.34262476])

In [35]:
arrRand / 4

array([-0.01751175, -0.01256272,  0.05209404, -0.17213518, -0.16782809])

In [36]:
1 / arrRand

array([-14.27612575, -19.90014475,   4.79901348,  -1.45234695,
        -1.48961949])

In [37]:
arrRand [(1)]

-0.05025089076036655

In [46]:
arr2d [1][2]

8

In [47]:
arr2d [1:2:2,::]

array([[ 6,  7,  8,  9, 10]])

In [48]:
np.sqrt (arr2d)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [49]:
arr2d * arr2d

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [50]:
arrRand.cumsum()

array([-0.07004702, -0.12029791,  0.08807825, -0.60046246, -1.27177483])

In [53]:
arr2d.sum()

55

In [54]:
arr2d.any()

True

In [55]:
arr2d.all()

True

In [59]:
a = np.array ([1,2,4,2,3])
a

array([1, 2, 4, 2, 3])

In [60]:
np.unique (a)

array([1, 2, 3, 4])

In [61]:
np.sort (a)

array([1, 2, 2, 3, 4])

In [62]:
np.where (a>2)

(array([2, 4]),)

In [67]:
np.where (a>2,"pass","fail")

array(['fail', 'fail', 'pass', 'fail', 'pass'], dtype='<U4')

In [65]:
arr2d.sum (axis = 1)

array([15, 40])

In [69]:
arr2df = arr2d.astype ("float")
arr2df

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [77]:
for x in arr2d:
    print (x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [78]:
arrJoin = np.concatenate((arr2d, arr2df))
arrJoin

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [79]:
arrStack =np.stack((arr2d, arr2df), axis=1)
arrStack

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 1.,  2.,  3.,  4.,  5.]],

       [[ 6.,  7.,  8.,  9., 10.],
        [ 6.,  7.,  8.,  9., 10.]]])

In [80]:
arrStackRow = np.hstack((arr2d, arr2df))
arrStackRow

array([[ 1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.,  6.,  7.,  8.,  9., 10.]])

In [81]:
arrStackCol = np.vstack((arr2d, arr2df))
arrStackCol

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [82]:
arrStackDepth = np.dstack((arr2d, arr2df))
arrStackDepth

array([[[ 1.,  1.],
        [ 2.,  2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.]],

       [[ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.],
        [10., 10.]]])

In [83]:
arrSplit = np.array_split(arr2d, 3)
arrSplit

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([], shape=(0, 5), dtype=int64)]

In [86]:
np.where (arrSplit ==4)

(array([], dtype=int64),)

In [88]:
arrCities = ["Karachi", "Lahore", "Islamabad", "Faisalabad"]
np.sort (arrCities)

array(['Faisalabad', 'Islamabad', 'Karachi', 'Lahore'], dtype='<U10')

In [92]:
np.power (arr2d, arr2df)

array([[1.00000000e+00, 4.00000000e+00, 2.70000000e+01, 2.56000000e+02,
        3.12500000e+03],
       [4.66560000e+04, 8.23543000e+05, 1.67772160e+07, 3.87420489e+08,
        1.00000000e+10]])

In [93]:
np.mod (arr2d, arr2df)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [94]:
np.remainder (arr2d, arr2df)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
np.divmod (arr2d, arr2df)

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [96]:
np.absolute (arr2d, arr2df)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [97]:
np.trunc(arr2df)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [100]:
np.around(arr2df,2)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [101]:
np.floor(arr2df)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [102]:
np.ceil (arr2d)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])